version: '3.8'

services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    container_name: service1-users
    ports:
      - "4001:3001"
    restart: unless-stopped

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: service2-products
    ports:
      - "4002:3002"
    restart: unless-stopped

  service3:
    build:
      context: ./service3
      dockerfile: Dockerfile
    container_name: service3-orders
    ports:
      - "4003:3003"
    restart: unless-stopped

  service4:
    build:
      context: ./service4
      dockerfile: Dockerfile
    container_name: service4-payments
    ports:
      - "4004:3004"
    restart: unless-stopped

  service5:
    build:
      context: ./service5
      dockerfile: Dockerfile
    container_name: service5-notifications
    ports:
      - "4005:3005"
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "4008:8080"
    depends_on:
      - service1
      - service2
      - service3
      - service4
      - service5
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:3000"
    depends_on:
      - api-gateway
    restart: unless-stopped

networks:
  default:
    name: microservices-simple-network
